// AUTO-GENERATED by AratBazar Bi-Hourly Intelligence Engine
// Last updated: 2026-09-11 at 2026-09-11T14:45:58.044Z
// Real-Time Fear & Greed: 56 (Greed)

export interface MarketAsset {
  symbol: string;
  name: string;
  price: string;
  change: string;
  changePercent: number;
  high24h: string;
  low24h: string;
  volume: string;
  marketCap?: string;
  category: 'indices' | 'stocks' | 'crypto' | 'commodities' | 'forex';
}

export const TICKER_ITEMS: MarketAsset[] = [
  {
    "symbol": "BTC/USDT",
    "name": "Bitcoin Spot",
    "price": "$78,727.2",
    "change": "+1.80%",
    "changePercent": 1.804,
    "high24h": "$79,890",
    "low24h": "$76,046.58",
    "volume": "$34.2B",
    "marketCap": "$1.76T",
    "category": "crypto"
  },
  {
    "symbol": "ETH/USDT",
    "name": "Ethereum Spot",
    "price": "$2,610.8",
    "change": "+6.89%",
    "changePercent": 6.891,
    "high24h": "$2,665.99",
    "low24h": "$2,432.88",
    "volume": "$18.5B",
    "marketCap": "$322B",
    "category": "crypto"
  },
  {
    "symbol": "SOL/USDT",
    "name": "Solana Spot",
    "price": "$103.33",
    "change": "+3.07%",
    "changePercent": 3.072,
    "high24h": "$105.8",
    "low24h": "$98",
    "volume": "$6.8B",
    "category": "crypto"
  },
  {
    "symbol": "XAU/USD",
    "name": "Gold Spot Bullion",
    "price": "$4,377.69",
    "change": "+0.46%",
    "changePercent": 0.464,
    "high24h": "$4,405.02",
    "low24h": "$4,302",
    "volume": "$182B",
    "category": "commodities"
  },
  {
    "symbol": "EUR/USD",
    "name": "Euro / US Dollar",
    "price": "1.0485",
    "change": "+0.14%",
    "changePercent": 0.14,
    "high24h": "1.0512",
    "low24h": "1.0460",
    "volume": "$480B",
    "category": "forex"
  },
  {
    "symbol": "USD/BDT",
    "name": "US Dollar / Bangladeshi Taka",
    "price": "123.25",
    "change": "+0.08%",
    "changePercent": 0.08,
    "high24h": "123.40",
    "low24h": "123.10",
    "volume": "$12.4M",
    "category": "forex"
  },
  {
    "symbol": "SPX",
    "name": "S&P 500 Index",
    "price": "5,865.40",
    "change": "+0.45%",
    "changePercent": 0.45,
    "high24h": "5,880.00",
    "low24h": "5,845.00",
    "volume": "$42.8B",
    "category": "indices"
  }
];
export const TOP_GAINERS: MarketAsset[] = [
  {
    "symbol": "BTC/USDT",
    "name": "Bitcoin Spot",
    "price": "$78,727.2",
    "change": "+1.80%",
    "changePercent": 1.804,
    "high24h": "$79,890",
    "low24h": "$76,046.58",
    "volume": "$34.2B",
    "marketCap": "$1.76T",
    "category": "crypto"
  },
  {
    "symbol": "ETH/USDT",
    "name": "Ethereum Spot",
    "price": "$2,610.8",
    "change": "+6.89%",
    "changePercent": 6.891,
    "high24h": "$2,665.99",
    "low24h": "$2,432.88",
    "volume": "$18.5B",
    "marketCap": "$322B",
    "category": "crypto"
  },
  {
    "symbol": "SOL/USDT",
    "name": "Solana Spot",
    "price": "$103.33",
    "change": "+3.07%",
    "changePercent": 3.072,
    "high24h": "$105.8",
    "low24h": "$98",
    "volume": "$6.8B",
    "category": "crypto"
  },
  {
    "symbol": "XAU/USD",
    "name": "Gold Spot Bullion",
    "price": "$4,377.69",
    "change": "+0.46%",
    "changePercent": 0.464,
    "high24h": "$4,405.02",
    "low24h": "$4,302",
    "volume": "$182B",
    "category": "commodities"
  }
];
export const TOP_LOSERS: MarketAsset[] = [];
export const MARKET_PULSE = {
  "fearGreedIndex": 56,
  "fearGreedLabel": "Greed",
  "marketRegime": "BULLISH_EXPANSION",
  "macroBias": "MODERATE RISK EXPANSION",
  "volatilityIndex": 14.8,
  "activeSessions": [
    "LONDON_OPEN",
    "NEW_YORK_ACTIVE"
  ]
};
