// AUTO-GENERATED by AratBazar Bi-Hourly Intelligence Engine
// Last updated: 2026-09-16 at 2026-09-16T09:00:32.215Z
// Real-Time Fear & Greed: 51 (Neutral)

export interface MarketAsset {
  symbol: string;
  name: string;
  price: string;
  change: string;
  changePercent: number;
  high24h: string;
  low24h: string;
  volume: string;
  marketCap?: string;
  category: 'indices' | 'stocks' | 'crypto' | 'commodities' | 'forex';
}

export const TICKER_ITEMS: MarketAsset[] = [
  {
    "symbol": "BTC/USDT",
    "name": "Bitcoin Spot",
    "price": "$75,730",
    "change": "-1.58%",
    "changePercent": -1.584,
    "high24h": "$77,343.44",
    "low24h": "$74,967.97",
    "volume": "$34.2B",
    "marketCap": "$1.76T",
    "category": "crypto"
  },
  {
    "symbol": "ETH/USDT",
    "name": "Ethereum Spot",
    "price": "$2,402.52",
    "change": "-2.95%",
    "changePercent": -2.951,
    "high24h": "$2,488.18",
    "low24h": "$2,358.88",
    "volume": "$18.5B",
    "marketCap": "$322B",
    "category": "crypto"
  },
  {
    "symbol": "SOL/USDT",
    "name": "Solana Spot",
    "price": "$97.04",
    "change": "-3.54%",
    "changePercent": -3.539,
    "high24h": "$101.39",
    "low24h": "$95.82",
    "volume": "$6.8B",
    "category": "crypto"
  },
  {
    "symbol": "XAU/USD",
    "name": "Gold Spot Bullion",
    "price": "$4,335.85",
    "change": "+1.60%",
    "changePercent": 1.599,
    "high24h": "$4,346.85",
    "low24h": "$4,266.67",
    "volume": "$182B",
    "category": "commodities"
  },
  {
    "symbol": "EUR/USD",
    "name": "Euro / US Dollar",
    "price": "1.0485",
    "change": "+0.14%",
    "changePercent": 0.14,
    "high24h": "1.0512",
    "low24h": "1.0460",
    "volume": "$480B",
    "category": "forex"
  },
  {
    "symbol": "USD/BDT",
    "name": "US Dollar / Bangladeshi Taka",
    "price": "123.25",
    "change": "+0.08%",
    "changePercent": 0.08,
    "high24h": "123.40",
    "low24h": "123.10",
    "volume": "$12.4M",
    "category": "forex"
  },
  {
    "symbol": "SPX",
    "name": "S&P 500 Index",
    "price": "5,865.40",
    "change": "+0.45%",
    "changePercent": 0.45,
    "high24h": "5,880.00",
    "low24h": "5,845.00",
    "volume": "$42.8B",
    "category": "indices"
  }
];
export const TOP_GAINERS: MarketAsset[] = [
  {
    "symbol": "XAU/USD",
    "name": "Gold Spot Bullion",
    "price": "$4,335.85",
    "change": "+1.60%",
    "changePercent": 1.599,
    "high24h": "$4,346.85",
    "low24h": "$4,266.67",
    "volume": "$182B",
    "category": "commodities"
  },
  {
    "symbol": "EUR/USD",
    "name": "Euro / US Dollar",
    "price": "1.0485",
    "change": "+0.14%",
    "changePercent": 0.14,
    "high24h": "1.0512",
    "low24h": "1.0460",
    "volume": "$480B",
    "category": "forex"
  },
  {
    "symbol": "USD/BDT",
    "name": "US Dollar / Bangladeshi Taka",
    "price": "123.25",
    "change": "+0.08%",
    "changePercent": 0.08,
    "high24h": "123.40",
    "low24h": "123.10",
    "volume": "$12.4M",
    "category": "forex"
  },
  {
    "symbol": "SPX",
    "name": "S&P 500 Index",
    "price": "5,865.40",
    "change": "+0.45%",
    "changePercent": 0.45,
    "high24h": "5,880.00",
    "low24h": "5,845.00",
    "volume": "$42.8B",
    "category": "indices"
  }
];
export const TOP_LOSERS: MarketAsset[] = [
  {
    "symbol": "BTC/USDT",
    "name": "Bitcoin Spot",
    "price": "$75,730",
    "change": "-1.58%",
    "changePercent": -1.584,
    "high24h": "$77,343.44",
    "low24h": "$74,967.97",
    "volume": "$34.2B",
    "marketCap": "$1.76T",
    "category": "crypto"
  },
  {
    "symbol": "ETH/USDT",
    "name": "Ethereum Spot",
    "price": "$2,402.52",
    "change": "-2.95%",
    "changePercent": -2.951,
    "high24h": "$2,488.18",
    "low24h": "$2,358.88",
    "volume": "$18.5B",
    "marketCap": "$322B",
    "category": "crypto"
  },
  {
    "symbol": "SOL/USDT",
    "name": "Solana Spot",
    "price": "$97.04",
    "change": "-3.54%",
    "changePercent": -3.539,
    "high24h": "$101.39",
    "low24h": "$95.82",
    "volume": "$6.8B",
    "category": "crypto"
  }
];
export const MARKET_PULSE = {
  "fearGreedIndex": 51,
  "fearGreedLabel": "Neutral",
  "marketRegime": "RANGE_EQUILIBRIUM",
  "macroBias": "MODERATE RISK EXPANSION",
  "volatilityIndex": 14.8,
  "activeSessions": [
    "LONDON_OPEN",
    "NEW_YORK_ACTIVE"
  ]
};
